### ISSUE TITLE
Overwrite issue?

### ISSUE THREAD

**Issue by Crustable** [Toom3000/ma3_Magic_ColorGrid#6]
Having an issue on setup where it will ask to overwrite for every single macro any time a selection is used. Not sure if this is only on 1.9.3.3 as this is what I'm using, and I know this was released for v1.8.8.2. I was able to correct the issue by adding a /o to every line, but this may be unnecessary. Any thoughts?

**Comment by Toom3000** [comment]
Hello Crustable,

sorry I have been busy and did not upgrade my own system for some time. Hopefully I have fixed the issue with 1.9.7.0 and also introduced a little feature called color flip. Maybe you could give the new release a shot and let me know if everything is working as expected.

Best Regards,

Thomas

**Comment by Crustable** [comment]
Sure thing, I will be happy to try it out tomorrow for sure! Thanks for the
update.
